const {router} = require('./../variables/variables.js');
const contacts = require('./contacts');
const chats = require('./chats');
const auth = require('./auth');
const settings = require('./settings');
router.use('/contacts', contacts);
router.use('/chats', chats);
router.use('/auth', auth);
router.use('/settings', settings);
module.exports = router;
